apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    {{- include "aetherdb.labels" . | nindent 4 }}
type: Opaque
stringData:
  AETHERDB_EMBED_API_KEY: {{ .Values.secrets.embedApiKey | quote }}
  AETHERDB_LLM_API_KEY: {{ .Values.secrets.llmApiKey | quote }}
  AETHERDB_LIBSQL_AUTH_TOKEN: {{ .Values.secrets.libsqlAuthToken | quote }}
