{{- if .Values.clickhouse.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-clickhouse
  labels:
    {{- include "aetherdb.labels" . | nindent 4 }}
    app.kubernetes.io/component: clickhouse
spec:
  type: ClusterIP
  ports:
    - port: 8123
      targetPort: http
      name: http
    - port: 9000
      targetPort: native
      name: native
  selector:
    app.kubernetes.io/component: clickhouse
    {{- include "aetherdb.selectorLabels" . | nindent 4 }}
{{- end }}
