[package]
name = "aetherdb-graph"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
aetherdb-domain = { path = "../domain" }
aetherdb-storage = { path = "../storage" }
tracing = { workspace = true }
uuid = { workspace = true }
libsql = "0.6"
